export const Categories = [
  'Fantasy',
  'Science Fiction',
  'Dystopian',
  'Action & Adventure',
  'Mystery',
  'Horror',
  'Thriller & Suspense',
  'Historical Fiction',
  'Romance',
  'Women’s Fiction',
  'Graphic Novel',
  'Short Story',
  'Memoir & Autobiography',
  'Biography',
  'Food & Drink',
  'Art & Photography',
  'Self-help',
  'History',
  'Travel',
  'True Crime',
  'Humor',
  'Essays',
  'Guide / How-to',
  'Science & Technology',
  'Children’s',
]
